W5D1/music_app/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:new ,:create ,:update ,:edit ,:destroy ,:index ,:show] do
    resources :albums, only: [:index] do
      resources :tracks, only: [:index]
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :albums, only: [:new ,:create ,:update ,:edit ,:destroy ,:show, :index]
  resources :tracks, only: [:new ,:create ,:update ,:edit ,:destroy ,:show, :index]

end

W5D1/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, presence: true

  belongs_to :band

  has_many :tracks
end

W5D1/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums

  has_many :tracks,
  through: :albums,
  source: :tracks

end

W5D1/music_app/app/models/track.rb
class Track < ApplicationRecord
  validates :title, :ord, presence: true

  belongs_to :album

  has_one :band,
  through: :album,
  source: :band
  
end

W5D1/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: { in: (6..20), allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if !user
    user.is_password?(password) ? user : nil
  end
end

W5D1/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    if params[:band_id]
      @bands = [Band.includes(:albums).find_by(id: params[:band_id])]
    else
      @bands = Band.all
    end
    render :index
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to bands_url
    else
      falsh.now['errors'] = @ablum.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update(album_params)
      redirect_to band_albums_url(band_id: @album.band_id)
    else
      falsh.now['errors'] = @ablum.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    band_id = @album.band_id
    if @album.destroy
      redirect_to band_albums_url(band_id: band_id)
    else

    end
  end

  private

  def album_params
    params.require(:album).permit([:band_id, :title, :year, :live])
  end
end

W5D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  before_action :require_login

  def log_in!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

W5D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(band_params)
      redirect_to bands_url
    else
      render :edit
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    if @band.destroy
      redirect_to bands_url
    else
      redirect_to bands_url
    end
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band
      render :show
    else
      redirect_to bands_url
    end
  end

  private
  def band_params
    params.require(:band).permit([:name])
  end
end

W5D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:email], params[:password])
    if @user
      log_in!(@user)
      redirect_to bands_url
    else
      @user = User.new
      flash.now['errors'] = ['Email or Password wrong']
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end


end

W5D1/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    if params[:album_id]
      @albums = [Album.includes(:tracks, :band).find_by(id: params[:album_id])]
      # @bands = [Band.includes(albums: :tracks).find_by(id: params[:band_id])]
    else
      @albums = Album.all.includes(:tracks, :band).order('bands.name ASC')
      # @bands = Band.all.includes(albums: :tracks)
    end
  end

  def new
    @track = Track.new
  end

  def update
    @track = Track.find_by(id: params[:id])
    if @track.update(track_params)
      redirect_to tracks_url
    else
      render :edit
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    if @track.destroy
      redirect_to tracks_url
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to bands_url
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  private
  def track_params
    params.require(:track).permit([:album_id, :title, :ord, :lyrics, :regular])
  end
end

W5D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to bands_url
    else
      flash.now['errors'] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private
  def user_params
    params.require(:user).permit([:email, :password])
  end

end

W5D1/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    auth_token = "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>"
    auth_token.html_safe
  end

  def controller?(*controller)
   controller.include?(params[:controller])
  end

 def action?(*action)
   action.include?(params[:action])
 end
 
end

W5D1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

W5D1/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/music_app/app/views/bands/_errors.html.erb
<% if flash[:errors] %>
  <ul class='errors'>
  <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
  <% end %>
  </ul>
<% end %>

W5D1/music_app/app/views/bands/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

W5D1/music_app/app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

W5D1/music_app/app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render 'errors' %>
<div class='form'>
  <form action="<%= band_url(@band) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name='_method' value='PATCH'>
    <input type="text" name="band[name]" value="<%= @band.name %>" placeholder="band name">
    <input type="submit" value="Update Band" class="submit">
  </form>
</div>

W5D1/music_app/app/views/bands/index.html.erb
<h1>Bands</h1>
<form action="<%= new_band_url %>" method="get">
  <%= auth_token %>
  <input type="submit" value="New" class='button'>
</form>

<table class='table'>

<% @bands.each do |band| %>
  <tr class='band_show'>
    <td><%= band.name %></td>
    <td class='table-buttons'><a href="<%= band_albums_url(band.id) %>" class='button-outline'> albums </a>
    <a href="<%= edit_band_url(band) %>" class='button-outline'> edit </a>
    <form action="<%= band_url(band) %>" method="post">
      <%= auth_token %>
      <input type="hidden" name='_method' value='DELETE'>
      <input type="submit" value="Delete" class='button-outline'>
    </form></td>
  </tr>
<% end %>
</table>

W5D1/music_app/app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'errors' %>
<div class='form'>
  <form action="<%= bands_url %>" method="post">
    <%= auth_token %>
    <input type="text" name="band[name]" value="<%= @band.name %>" placeholder="band name">
    <input type="submit" value="Create Band" class="submit">
  </form>
</div>

W5D1/music_app/app/views/bands/show.html.erb
<h1>@band.name</h1>

W5D1/music_app/app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

W5D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <a href="<%= bands_url %>"><h1 class='title'> Music App </h1> </a>
      <% if logged_in? %>
      <ul class='sections'>
        <li><a href="<%= bands_url %>"  class='<% if controller?("bands") %> selected <% end %>  button-white'> bands </a></li>
        <li><a href="<%= albums_url %>" class='<% if controller?("albums") %> selected <% end %>  button-white'> albums </a></li>
        <li><a href="<%= tracks_url %>" class='<% if controller?("tracks") %> selected <% end %>  button-white'> tracks </a></li>
      </ul>
      <% end %>
      <ul class='user_info'>
        <% if logged_in? %>
        <li class='button'><a href="<%= user_url(current_user) %>"> <%= current_user.email %> </a> </li>
        <li>
          <form action="<%= session_url %>" method="post" >
            <%= auth_token %>
            <input type="hidden" name='_method' value='DELETE'>
            <input type="submit" value="log out" class='button-white'>
          </form>
      </li>
        <% else %>
      <li>
        <form action="<%= new_session_url %>" method="get" >
          <%= auth_token %>
          <input type="submit" value="sign in" class='button-white'>
        </form>
    </li>

      <li>
        <form action="<%= new_user_url %>" method="get" >
          <%= auth_token %>
          <input type="submit" value="sign up" class='button-white'>
        </form>
    </li>
        <% end %>
      </ul>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

W5D1/music_app/app/views/tracks/_errors.html.erb
<% if flash[:errors] %>
  <ul class='errors'>
  <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
  <% end %>
  </ul>
<% end %>

W5D1/music_app/app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render 'errors' %>
<div class='form'>
  <form action="<%= track_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name='_method' value='PATCH'>
    <label for="title">Title</label>
    <input id='title' type="text" name="track[title]" value="<%= @track.title %>" placeholder="title">
    <label for="ord">Ord</label>
    <input id='ord' type="text" name="track[ord]" value="<%= @track.ord %>" placeholder="ord">


      <label for="regular">Bonus?: </label>
      <input type="checkbox" name="track[regular]" value="false" id="regular">

      <label for="album">Album: </label>
      <select id='album' name="track[album_id]">
        <% Album.all.each do |album| %>
        <option value="<%= album.id %>"><%= album.title %></option>
        <% end %>
      </select>

    <label for="lyrics">Lyrics</label>
    <textarea id='lyrics' name="track[lyrics]" rows="8" cols="80"><%= @track.lyrics %></textarea>

    <input type="submit" value="Save Changes" class="button submit">
  </form>
</div>

W5D1/music_app/app/views/tracks/index.html.erb
<h1>Tracks</h1>

<!-- <%# @bands.each do |band|  %>
<h2><%#= band.name %></h2> -->
<% @albums.each do |album|  %>
<% if album.tracks.length > 0 %>
<h2><%= album.title %> by <%= album.band.name %></h2>
<table class='table'>
  <% album.tracks.each do |track| %>
    <tr>
     <td><%= track.title %></td>
     <td><%= track.ord %></td>
     <td><%= track.regular %></td>
     <td class="table-buttons"><a href="<%= edit_track_url(track) %>" class='button-outline'> edit </a>
       <form action="<%= track_url(track) %>" method="post">
       <%= auth_token %>
       <input type="hidden" name='_method' value='DELETE'>
       <input type="submit" value="Delete" class='button-outline'>
     </form></td>
   </tr>
  <% end %>

</table>

<% end %>

<% end  %>
<!-- <%# end %> -->

<form action="<%= new_track_url %>" method="get">
  <%= auth_token %>
  <input type="submit" value="New" class='big'>
</form>

W5D1/music_app/app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'errors' %>
<div class='form'>
  <form action="<%= tracks_url %>" method="post">
    <%= auth_token %>

    <input type="text" name="track[title]" value="<%= @track.title %>" placeholder="title">
    <input type="text" name="track[ord]" value="<%= @track.ord %>" placeholder="ord">

    <div class="radios">
      <label for="regular">Bonus?: </label>
      <input type="checkbox" name="track[regular]" value="false" id="regular">

      <label for="album">Album: </label>
      <div class="select-style">
        <select id='album' name="track[album_id]">
          <% Album.all.each do |album| %>
          <option value="<%= album.id %>"><%= album.title %></option>
          <% end %>
        </select>
      </div>
    </div>

    <textarea name="track[lyrics]" rows="8" cols="80"></textarea>

    <input type="submit" value="Create Track" class="submit">
  </form>
</div>

W5D1/music_app/app/views/users/_errors.html.erb
<% if flash[:errors] %>
  <ul class='errors'>
  <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
  <% end %>
  </ul>
<% end %>

W5D1/music_app/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'errors' %>
<div class='form'>
  <form action="<%= users_url %>" method="post">
    <%= auth_token %>
    <label for="email">Email</label>
    <input id="email" type="text" name="user[email]" value="<%= @user.email %>" placeholder="email">
    <label for="password">Password</label>
    <input id='password' type="password" name="user[password]" value="<%= @user.password %>" placeholder="password">
    <input type="submit" value="Sign Up" class="button submit">
  </form>
</div>

W5D1/music_app/app/views/users/show.html.erb
<h1> Hello <%= @user.email %> </h1>